sList = [
    "science",
    "carl sagan",
    "carl sagan quotes",
    "universe",
    "stars",
    "planets",
    "molecule",
    "atom",
    "earth",
    "galaxy",
    "light",
    "space",
    "jupiter",
    "nature",
    "solar system",
    "solar wind",
    "experiments",
    "energy",
    "gravity",
    "biosynthesis",
    "hack",
    "carbon",
    "chromosome",
    "electricity",
    "dna",
    "elasticity",
    "electron",
    "electromagnetic waves",
    "electrolyte",
    "entropy",
    "enzyme",
    "evolution",
    "chemistry",
    "biology",
    "frequency",
    "particle",
    "fusion",
    "gametes",
    "genes",
    "half-life",
    "inertia",
    "ions",
    "isotope",
    "magnet",
    "moon",
    "sun",
    "mitochondria",
    "momentum",
    "neutron",
    "newton",
    "neil degrasse tyson quotes",
    "nucleus",
    "ozone",
    "photon",
    "protein",
    "quantum",
    "quarks",
    "radioactivity",
    "relativity",
    "standard model",
    "viscocity",
]